# Generated by Django 4.2.4 on 2023-08-31 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagweb', '0004_profesor_imagen_alter_avatar_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
