# Generated by Django 4.2.4 on 2023-08-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagweb', '0011_alter_post_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
