# Generated by Django 4.2.4 on 2023-09-01 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagweb', '0012_post_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
