# Generated by Django 4.2.4 on 2023-09-01 19:48

from django.db import migrations, models
import django.utils.timezone
import pagweb.models


class Migration(migrations.Migration):

    dependencies = [
        ('pagweb', '0013_alter_avatar_imagen_alter_profesor_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', pagweb.models.CustomUserManager()),
            ],
        ),
    ]
