# Generated by Django 4.2.4 on 2023-09-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagweb', '0015_remove_profesor_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/'),
        ),
    ]
